### ISSUE TITLE
Add more buttons

### ISSUE THREAD

**Issue by crazymind90** [TimOliver/TOAlertViewController#1]
This is the most beautiful Alert I'v ever seen ..
BUT , I can not add more than 2 buttons or use one single button 
Please fix that as soon as you could , I'm not going to release my tweak without this beauty

**Comment by TimOliver** [comment]
Hey @crazymind90! Wow! Thanks so much for the kind words! I'm really glad you like it that much! 😁

Oh snap! I just tried setting a single button, and it crashed. That's certainly a bug. Thanks so much for letting me know!

I'll have a look at the button layout logic and try and refactor it so it's smart enough to support any number of buttons. I'll try and have it done this week.

Thanks for that!

**Comment by TimOliver** [comment]
Done. :) https://github.com/TimOliver/TOAlertViewController/pull/2

Try pulling from `master` and let me know what you think. :)

**Comment by crazymind90** [comment]
<img width="583" alt="Aw" src="https://user-images.githubusercontent.com/32680361/73349340-100f7000-429c-11ea-91ba-8babad9eec92.png">

Dude , This is amazing 😍😍 Animations , Colors ..... everything is Perfect ❤️

**Comment by TimOliver** [comment]
Haha yay! Glad it's working and glad you like it!

Ohhh... that being said, I wonder how that looks in landscape rotations. I'll probably need to add a scroll view or something...

**Comment by TimOliver** [comment]
Ahh. Yep. That's super broken. 😅

![Screen Shot 2020-01-29 at 22 51 44](https://user-images.githubusercontent.com/429119/73362304-f9900580-42e9-11ea-8234-22f4bf52be66.png)

Anyway. This particular issue is fixed, but I might need to open a new issue to tackle handling when it overflows the screen.

Thanks again for your help @crazymind90!
